services:
  qdrant:
    image: qdrant/qdrant
    deploy:
      resources:
        limits:
          memory: 8G
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333"]
      
  ollama:
    image: ollama/ollama
    deploy:
      resources:
        devices:
          - driver: nvidia
            count: 1

  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    environment:
      - QDRANT_URL=qdrant:6333
      - OLLAMA_URL=ollama:11434
    depends_on:
      qdrant:
        condition: service_healthy
      ollama:
        condition: service_started

volumes:
  qdrant_data:
  ollama_models:

networks:
  saas-net:
    driver: overlay